@baseURL = http://localhost:5128

###
# @name createClient
POST {{baseURL}}/api/clients
Content-Type: application/json

{
  "name": "natan",
  "email": "natan@tese.com"
}
###
@clientId = {{createClient.response.body.id}}
###
GET {{baseURL}}/api/clients
###
GET {{baseURL}}/api/clients/{{clientId}}
###
PUT {{baseURL}}/api/clients/{{clientId}}
Content-Type: application/json

{
  "name": "natan updated",
  "email": "natan@santos.com"
}

###
DELETE {{baseURL}}/api/clients/{{clientId}}

###
# @name createProoduct
POST {{baseURL}}/api/products/{{clientId}}
Content-Type: application/json

{
  "name": "caneta",
  "brand": "Bic",
  "price": 2
}
